package com.yllyx.clubs.entity;
// Generated 2016-3-28 21:11:41 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * User generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "user", catalog = "clubs",
    uniqueConstraints = {@UniqueConstraint(columnNames = "email"),
        @UniqueConstraint(columnNames = "name"), @UniqueConstraint(columnNames = "telephone")})
public class User implements java.io.Serializable
{

    private String id;

    private String name;

    private String passwd;

    private String telephone;

    private String email;

    public User()
    {}

    public User(String id, String name, String passwd)
    {
        this.id = id;
        this.name = name;
        this.passwd = passwd;
    }

    public User(String id, String name, String passwd, String telephone, String email)
    {
        this.id = id;
        this.name = name;
        this.passwd = passwd;
        this.telephone = telephone;
        this.email = email;
    }

    @Id
    @GenericGenerator(name = "idGenerator", strategy = "uuid")
    @GeneratedValue(generator = "idGenerator")
    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "passwd", nullable = false)
    public String getPasswd()
    {
        return this.passwd;
    }

    public void setPasswd(String passwd)
    {
        this.passwd = passwd;
    }

    @Column(name = "telephone", unique = true, length = 20)
    public String getTelephone()
    {
        return this.telephone;
    }

    public void setTelephone(String telephone)
    {
        this.telephone = telephone;
    }

    @Column(name = "email", unique = true)
    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

}
