package com.yllyx.clubs.entity;
// Generated 2016-3-28 21:11:41 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * Userinfo generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "userinfo", catalog = "clubs")
public class UserInfo implements java.io.Serializable
{

    /**
     * serialVersionUID<br>
     */
    private static final long serialVersionUID = 8056247895385602629L;

    private String id;

    private String qq;

    private String weixin;

    private String weibo;

    private String address;

    private String icon;

    private String sign;

    public UserInfo()
    {}

    public UserInfo(String id)
    {
        this.id = id;
    }

    public UserInfo(String id, String qq, String weixin, String weibo, String address, String icon,
                    String sign)
    {
        this.id = id;
        this.qq = qq;
        this.weixin = weixin;
        this.weibo = weibo;
        this.address = address;
        this.icon = icon;
        this.sign = sign;
    }

    @Id
    @GenericGenerator(name = "idGenerator", strategy = "uuid")
    @GeneratedValue(generator = "idGenerator")
    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    @Column(name = "qq", length = 30)
    public String getQq()
    {
        return this.qq;
    }

    public void setQq(String qq)
    {
        this.qq = qq;
    }

    @Column(name = "weixin", length = 30)
    public String getWeixin()
    {
        return this.weixin;
    }

    public void setWeixin(String weixin)
    {
        this.weixin = weixin;
    }

    @Column(name = "weibo", length = 30)
    public String getWeibo()
    {
        return this.weibo;
    }

    public void setWeibo(String weibo)
    {
        this.weibo = weibo;
    }

    @Column(name = "address", length = 100)
    public String getAddress()
    {
        return this.address;
    }

    public void setAddress(String address)
    {
        this.address = address;
    }

    @Column(name = "icon", length = 100)
    public String getIcon()
    {
        return this.icon;
    }

    public void setIcon(String icon)
    {
        this.icon = icon;
    }

    @Column(name = "sign")
    public String getSign()
    {
        return this.sign;
    }

    public void setSign(String sign)
    {
        this.sign = sign;
    }

}
